from datetime import datetime  #用於處理 Python 原生的日期時間物件，特別是在模型實例化時給 created_at 等欄位賦予預設值。
from typing import Optional, List  #雖然此處未直接使用（僅供參考），但在大型專案中可為變數提供型別提示，幫助 IDE 進行自動補全與型別檢查。
from sqlalchemy import (
    Column, String, Integer, Boolean, DateTime, Text, ForeignKey, DECIMAL, JSON, UniqueConstraint, Index, desc
)
#解釋：從 SQLAlchemy 核心匯入欄位型別定義與約束工具。e.g.  Column：定義資料表「欄位」的基底、String、Integer 等：對應資料庫的資料型態、Index：手動建立複合索引以加速特定查詢。
from sqlalchemy.dialects.postgresql import UUID #這裡特別導入專屬的 UUID 型別。它讓資料庫原生儲存 UUID，比儲存為字串更節省空間且查詢更快。
from sqlalchemy.orm import declarative_base, relationship
#declarative_base：建立模型繼承的「基底類別」。所有資料表模型都要繼承它，SQLAlchemy 會自動根據類別定義產生對應的 CREATE TABLE 語句。
#relationship：定義模型之間的「物件導向關聯」，讓你可以用 user.sessions 這樣的方式直接存取關聯資料，而不必手動寫 JOIN。
import uuid

# declare base type, all model inherit from here 
Base = declarative_base()

#user model 
class User(Base): 
    """"User account model = stores profile, game stats and wallet address."""
    __tablename__ = "users" #對應database 的 users 資料表，指定這個類別在資料庫中的實際表格名稱，如果不指定，SQLAlchemy 會自動將類別名稱轉為小寫（但這裡明確指定為 users 複數形式）

    id = Column(UUID(as_uuid = True), primary_key = True, default = uuid.uuid4) # UUID(as_uuid=True)：告訴 SQLAlchemy 在 Python 端使用 uuid.UUID 物件，而非純字串、primary key UUID v4 generated by Python, 當新增資料沒有提供 ID 時，Python 會執行此函式產生隨機 UUID。注意：這由 Python 端產生，若想交由資料庫產生需改用 server_default
    email = Column(String(255), unique = True, nullable = False, index = True)   #index=True：建立 B-Tree 索引。因為登入功能極度依賴 Email 查詢，加索引能大幅加速 WHERE 條件。
    username = Column(String(50), unique = True, nullable = False, index = True) # 使用者名稱，邏輯同上。長度 50，唯一且必填，加索引（常用於個人頁面網址查詢）。
    password_hash = Column(String(255))
    display_name = Column(String(100)) #顯示名稱, 不建索引因為不常作為查詢條件。
    avatar_url = Column(Text)
    wallet_address  = Column(String(42), unique = True, index = True) #我覺得錢包並不是MVP開發重點
    role = Column(String(20), default = "player")
    level = Column(Integer, default = 1)
    xp = Column (Integer, default = 0)
    sport_tokens = Column(DECIMAL (20,8), default = 0)
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow) #在新增時設為當前時間，且當更新發生時（onupdate），自動更新為當下時間。這讓你知道資料最後是何時被修改的。

    #定義與其他模型的雙向關聯。
    # back_populates：對應到對方模型中的關聯變數名稱（如 GameSession 中有一個 user 屬性）。
    # cascade="all, delete-orphan"：當使用者被刪除時，自動刪除所有關聯的會話、俱樂部成員資格、每日記錄和視覺會話。這確保資料庫沒有孤兒資料（外鍵約束雖然有 CASCADE，但這裡是 ORM 層級的連動，可確保 Python 物件的同步）。
    sessions = relationship("GameSession", back_populates="user", cascade="all, delete-orphan")
    club_memberships = relationship("ClubMember", back_populates="user", cascade="all, delete-orphan")
    daily_records = relationship("DailyRecord", back_populates="user", cascade="all, delete-orphan")
    vision_sessions = relationship("VisionSession", back_populates="user", cascade="all, delete-orphan")

class GameMode(Base):
    __tablename__ = "game_modes"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    slug = Column(String(30), unique=True, nullable=False, index=True) #放在 URL 中作為路徑參數（如 /game/soccer-battle）。因為查詢極度頻繁，加上了 unique 與 index。
    name = Column(String(100), nullable=False)
    description = Column(Text)
    category = Column(String(20))
    scoring_rules = Column(JSON, default=dict) #計分規則儲存為 JSON。因不同遊戲計分邏輯（如籃球 vs 足球）差異極大，無法用固定欄位表示，使用 JSON 可動態儲存參數（如 {"goal": 3, "assist": 1}）。預設為空字典。
    is_active = Column(Boolean, default = True)
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    sessions = relationship("GameSession", back_populates="game_mode") #一對多的關聯（一個模式可以有多個遊戲會話和視覺會話）。這裡沒有設定 cascade，因為刪除遊戲模式時，通常應保留歷史紀錄（或不允許刪除模式），以免破壞統計數據。
    vision_sessions = relationship("VisionSession", back_populates="game_mode")

class GameSession(Base):
    __tablename__ = "game_sessions"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False) # 外鍵欄位，分別指向使用者與遊戲模式。在資料庫層級設定，當使用者被刪除時，該使用者的所有遊戲會話自動被資料庫刪除，保持引用完整性（這與前面 ORM 的 cascade 相互配合）。
    game_mode_id = Column(UUID(as_uuid=True), ForeignKey("game_modes.id"), nullable=False)
    score = Column(Integer, default=0)
    combo_max = Column(Integer, default=0)
    accuracy = Column(DECIMAL(5, 2), default=0)
    duration_seconds = Column(Integer, default=0)
    replay_url = Column(Text)
    session_metadata = Column(JSON, default=dict)
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    user = relationship("User", back_populates="sessions")
    game_mode = relationship("GameMode", back_populates="sessions")
    __table_args__ = (
        Index("idx_sessions_user_created", "user_id", desc("created_at")),
        Index("idx_sessions_game_score", "game_mode_id", desc("score")),
        Index("idx_sessions_created", desc("created_at")),  # 使用 desc() 函數

    )
    #for performance, 
    # 第一個索引：(user_id, created_at DESC)。常用於「查詢某用戶最近的遊戲紀錄（ORDER BY created_at DESC）」。複合索引讓查詢可以直接在索引中完成排序，無需額外排序（Using index）。
    # 第二個索引：(game_mode_id, score DESC)。常用於「查詢某遊戲模式的排行榜（ORDER BY score DESC）」。
    # 使用 DESC 因為我們幾乎總是看最新或最高分，這符合 B-Tree 索引的排序方向，效率最高。

class Club(Base):
    __tablename__ = "clubs"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(100), nullable=False)
    slug = Column(String(50), unique=True, nullable=False, index=True)
    description = Column(Text)
    avatar_url = Column(Text)
    banner_url = Column(Text)
    owner_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    member_count = Column(Integer, default=0)
    #冗餘計數欄位。為了避免每次查詢俱樂部都要 COUNT 成員，這裡直接儲存數量。但維護成本高，需在增刪成員時手動更新此值（可用觸發器或應用層邏輯確保一致）。
    is_verified = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    members = relationship("ClubMember", back_populates="club", cascade="all, delete-orphan")

class ClubMember(Base):
    __tablename__ = "club_members"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    club_id = Column(UUID(as_uuid=True), ForeignKey("clubs.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    role = Column(String(20), default="member")
    joined_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    club = relationship("Club", back_populates="members")
    user = relationship("User", back_populates="club_memberships")
    #relationship() 不是資料庫層的東西(資料庫層是靠 ForeignKey 建立關聯),而是 ORM 層的語法糖,讓你可以直接用物件屬性存取關聯資料,
    #back_populates 填的是「對方 class 上,指回自己這個 relationship 的屬性名稱」,不是自己這邊的名稱。所以要完整看懂,你要看 Club 和 User 這兩個 model 怎麼定義的,
    __table_args__ = (UniqueConstraint("club_id", "user_id"),)

class DailyRecord(Base):
    __tablename__ = "daily_records"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    record_type = Column(String(30), nullable=False)
    value = Column(DECIMAL(12, 2), nullable=False)
    unit = Column(String(20), nullable=False)
    note = Column(Text)
    recorded_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    user = relationship("User", back_populates="daily_records")

class Event(Base):
    __tablename__ = "events"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title = Column(String(200), nullable=False)
    slug = Column(String(100), unique=True, nullable=False, index=True)
    description = Column(Text)
    event_type = Column(String(20))
    game_mode_id = Column(UUID(as_uuid=True), ForeignKey("game_modes.id"))
    start_at = Column(DateTime(timezone=True), nullable=False)
    end_at = Column(DateTime(timezone=True), nullable=False)
    venue = Column(String(200))
    max_participants = Column(Integer)
    ticket_price = Column(DECIMAL(10, 2), default=0)
    ticket_currency = Column(String(10), default="USD")
    status = Column(String(20), default="upcoming")
    created_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)

class EventParticipant(Base):
    __tablename__ = "event_participants"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    event_id = Column(UUID(as_uuid=True), ForeignKey("events.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    ticket_tx_hash = Column(String(66))
    checked_in_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    __table_args__ = (UniqueConstraint("event_id", "user_id"),)

class ThemeCollection(Base):
    __tablename__ = "theme_collections"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(100), nullable=False)
    slug = Column(String(50), unique=True, nullable=False, index=True)
    ip_partner = Column(String(100))
    season = Column(String(20))
    start_date = Column(DateTime(timezone=True))
    end_date = Column(DateTime(timezone=True))
    assets = Column(JSON, default=list)   
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)

class VisionSession(Base):
    """Stores results from a vision training session (pose detection)."""
    __tablename__ = "vision_sessions"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    game_mode_id = Column(UUID(as_uuid=True), ForeignKey("game_modes.id"), nullable=False)
    reference_video_url = Column(Text)
    average_similarity = Column(DECIMAL(5, 2), default=0)
    best_combo = Column(Integer, default=0)
    total_frames = Column(Integer, default=0)
    good_frame_pct = Column(DECIMAL(5, 2), default=0)
    joint_deviations = Column(JSON, default=dict)
    session_metadata = Column(JSON, default=dict)
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    user = relationship("User", back_populates="vision_sessions")
    game_mode = relationship("GameMode", back_populates="vision_sessions")
    __table_args__ = (
        Index("idx_vision_user_created", "user_id", desc("created_at")),
        Index("idx_vision_game_sim", "game_mode_id", desc("average_similarity")),
        
    )