export const copy = {
  en: {
    nav: {
      train: "Train",
      time: "By time",
      focus: "By focus",
      studio: "Paste a link",
      progress: "History",
      club: "Clubs",
      guide: "Guide",
      about: "About",
      streak: "{n} day streak",
    },
    lang: { zh: "中文", en: "EN" },
    home: {
      eyebrow: "linksparks",
      title: "Train with Pamela",
      lede: "Gestures can pause, play, switch the layout, and rewind 10 seconds.",
      browse: "Browse Pamela workouts",
      guide: "How to use",
      paste: "Paste a YouTube link",
      sessions: "sessions",
      minutes: "minutes",
      nowFit: "Suggested for now",
      byTime: "By time of day",
      byTimeHint: "Pick a slot that fits your day — wake-up, a no-sweat lunch break, or wind-down before bed.",
      byFocus: "By body focus",
      byFocusHint: "Target abs, neck and shoulders, back, hamstrings from sitting, or a round-back posture.",
      quick: "Quick picks",
      defaultLayout: "Default layout: {layout}",
      standing: "standing",
      mat: "mat",
    },
    train: {
      title: "Pamela Reif",
      lede: "Workouts grouped by type. Open one to split the screen with your mirror.",
      crumb: "Train",
    },
    collection: {
      timeIndex: "By time of day",
      timeLede: "Three windows: morning energy, a midday session that will not soak your clothes, and a calm wind-down before sleep.",
      focusIndex: "By body focus",
      focusLede: "Choose a muscle group or a desk-life goal. Each list is a short Pamela set you can finish in one sitting.",
      workouts: "{n} workouts",
      backTime: "All time slots",
      backFocus: "All focuses",
    },
    time: {
      morning: {
        name: "Morning",
        blurb: "Wake the body without a full gym session. Standing cardio and short stretches.",
      },
      midday: {
        name: "Midday · no sweat",
        blurb: "Office-friendly mobility and low-impact work. Stay presentable after lunch.",
      },
      evening: {
        name: "Evening · before bed",
        blurb: "Slow stretch and posture work so you can cool down instead of spike your heart rate.",
      },
    },
    focus: {
      abs: {
        name: "Abs",
        blurb: "Core sessions from beginner to six-pack. Mat layout by default.",
      },
      neck: {
        name: "Neck & shoulders",
        blurb: "Open the chest and unload the neck after screens and a forward head.",
      },
      back: {
        name: "Back",
        blurb: "Upper and lower back strength plus stretch for a more stable spine.",
      },
      hamstrings: {
        name: "Hamstrings · desk life",
        blurb: "Posterior chain and hip openers for people who sit most of the day.",
      },
      posture: {
        name: "Undo a round back",
        blurb: "Counter the desk slump: chest open, mid-back, and a taller stance.",
      },
    },
    studio: {
      title: "Paste a YouTube link",
      lede: "Pamela Reif is the main catalog. If a pasted video is blocked by YouTube, pick one from Train instead.",
      label: "YouTube URL",
      load: "Load",
      error: "Paste a YouTube URL.",
      custom: "Custom YouTube",
    },
    progress: {
      title: "History",
      summary: "{count} sessions, {minutes} minutes, {streak} day streak.",
      clear: "Clear all",
      empty: "No sessions yet.",
      delete: "Delete",
    },
    club: {
      title: "Clubs",
      lede: "Join a crew. Your name shows in the header.",
      people: "{n} people",
      join: "Join",
      joined: "Joined",
    },
    account: {
      title: "Your name",
      lede: "No account required. This is only stored on this device.",
      label: "Display name",
      placeholder: "Your name",
      save: "Save",
      guest: "Guest",
    },
    trainer: {
      standing: "Standing · left / right",
      mat: "Mat · top / bottom",
      legend:
        "Open palm pause · thumbs up play · peace switch layout · thumbs down or point up rewind 10s",
      last: "last: {g}",
      end: "End session",
      you: "You",
      coach: "Pamela",
      mirror: "Mirror",
      cameraOff: "Camera off",
      cameraNeed: "Allow the camera to use the mirror.",
      gestureNet: "Gestures need the camera and a network connection.",
      paused: "Paused",
      playing: "Playing",
      switched: "Layout switched",
      rewound: "Rewound 10 seconds",
      mirrorOn: "Mirror on",
    },
    gesture: {
      pause: "pause",
      play: "play",
      switch: "switch",
      rewind: "rewind 10s",
    },
    guide: {
      title: "How to use",
      lede: "Stand in the camera so your hand is clearly visible. Hold one gesture for a moment — the same hand should not fire twice within about a second.",
      pauseName: "Pause",
      pauseHow: "Open palm, facing the camera.",
      playName: "Play",
      playHow: "Thumbs up.",
      switchName: "Switch layout",
      switchHow: "Peace sign (index and middle finger). Standing is left / right; mat is coach on top, you below.",
      rewindName: "Rewind 10 seconds",
      rewindHow: "Thumbs down or point up. The video jumps back ten seconds.",
      tipTitle: "Tips",
      tip1: "Allow the camera when the browser asks. The mirror stays on this device.",
      tip2: "One hand at a time works more reliably than two.",
      tip3: "If a YouTube video will not embed, pick a Pamela session from Train.",
    },
    about: {
      title: "About this site",
      p1: "Hi, I’m 語仁 Rain Liu!",
      p2: "I made this site because I like doing Pamela Reif’s home workouts.",
      p3: "Walking back to the computer to skip and pause was too much hassle (yes, even while exercising). I wanted a page that makes picking a session and controlling it easier.",
      p4: "About 99% of the code was written with Cursor Agent; see the GitHub repo. Fully open source, not for profit.",
      p5: "Aside from links you paste yourself, every default video is Pamela’s teaching material on YouTube.",
      p6: "Not affiliated with Pamela Reif. If you enjoy this content, support her on YouTube.",
    },
    yt: {
      blocked: "YouTube blocked embedding for this video.",
      open: "Open {title} on YouTube",
      fallback: "this workout",
      hint: "Use a Pamela session from Train — those are checked for embed.",
    },
  },
  zh: {
    nav: {
      train: "訓練",
      time: "時段",
      focus: "部位",
      studio: "貼上連結",
      progress: "紀錄",
      club: "社團",
      guide: "教學",
      about: "關於",
      streak: "連續 {n} 天",
    },
    lang: { zh: "中文", en: "EN" },
    home: {
      eyebrow: "linksparks",
      title: "跟 Pamela 一起練",
      lede: "手勢可暫停、播放、切換版面、倒帶10秒。",
      browse: "瀏覽 Pamela 課表",
      guide: "使用教學",
      paste: "貼上 YouTube 連結",
      sessions: "堂課",
      minutes: "分鐘",
      nowFit: "現在適合",
      byTime: "依時段",
      byTimeHint: "依一天的節奏選課：早上喚醒、中午不流汗、晚上睡前收工。",
      byFocus: "依部位與功能",
      byFocusHint: "腹肌、肩頸、背部肌群、久坐的大腿後側，或改善駝背。",
      quick: "快速展示",
      defaultLayout: "預設版面：{layout}",
      standing: "站姿左右",
      mat: "墊上上下",
    },
    train: {
      title: "Pamela Reif",
      lede: "依訓練類型分組。點進一堂課，就能和鏡子分屏跟練。",
      crumb: "訓練",
    },
    collection: {
      timeIndex: "依時段",
      timeLede: "三個時段：早上喚醒、中午不弄濕衣服、晚上睡前放慢。",
      focusIndex: "依部位與功能",
      focusLede: "選一個肌群或久坐目標。每份清單都是可以一次做完的 Pamela 短課。",
      workouts: "{n} 堂課",
      backTime: "全部時段",
      backFocus: "全部部位",
    },
    time: {
      morning: {
        name: "早上",
        blurb: "喚醒身體，不必當成完整重訓。站姿有氧與短伸展。",
      },
      midday: {
        name: "中午 · 不流汗",
        blurb: "適合辦公室的活動度與低衝擊。午休後仍可見人。",
      },
      evening: {
        name: "晚上 · 睡前",
        blurb: "慢伸展與體態練習，讓心率降下來，而不是再拉高。",
      },
    },
    focus: {
      abs: {
        name: "腹肌 Abs",
        blurb: "從初階到六塊肌的核心課。預設墊上版面。",
      },
      neck: {
        name: "肩頸",
        blurb: "螢幕與前傾頭頸之後，打開胸口、卸掉肩頸緊繃。",
      },
      back: {
        name: "背部肌群",
        blurb: "上背與下背的力量與伸展，讓脊椎更穩。",
      },
      hamstrings: {
        name: "大腿後肌 · 久坐",
        blurb: "針對久坐族群的後側鏈與髖關節打開。",
      },
      posture: {
        name: "改善駝背",
        blurb: "反轉桌前塌肩：開胸、中背，站得更高。",
      },
    },
    studio: {
      title: "貼上 YouTube 連結",
      lede: "主目錄是 Pamela Reif。若貼上的影片被 YouTube 禁止內嵌，請改從訓練頁選課。",
      label: "YouTube 網址",
      load: "載入",
      error: "請貼上 YouTube 網址。",
      custom: "自訂 YouTube",
    },
    progress: {
      title: "紀錄",
      summary: "{count} 堂課、{minutes} 分鐘、連續 {streak} 天。",
      clear: "全部清除",
      empty: "還沒有訓練紀錄。",
      delete: "刪除",
    },
    club: {
      title: "社團",
      lede: "加入一個小隊。你的名字會顯示在頁首。",
      people: "{n} 人",
      join: "加入",
      joined: "已加入",
    },
    account: {
      title: "你的名字",
      lede: "不必註冊帳號。只存在這台裝置上。",
      label: "顯示名稱",
      placeholder: "你的名字",
      save: "儲存",
      guest: "訪客",
    },
    trainer: {
      standing: "站姿 · 左／右",
      mat: "墊上 · 上／下",
      legend:
        "張開手掌暫停 · 豎拇指播放 · 勝利手勢Ｖ切換版面 · 拇指朝下或食指朝上倒帶10秒",
      last: "剛才：{g}",
      end: "結束這堂課",
      you: "你",
      coach: "Pamela",
      mirror: "鏡子",
      cameraOff: "鏡頭關閉",
      cameraNeed: "請允許鏡頭，才能使用鏡子。",
      gestureNet: "手勢需要鏡頭與網路連線。",
      paused: "已暫停",
      playing: "播放中",
      switched: "已切換版面",
      rewound: "已倒帶 10 秒",
      mirrorOn: "鏡子已開啟",
    },
    gesture: {
      pause: "暫停",
      play: "播放",
      switch: "切換",
      rewind: "倒帶 10 秒",
    },
    guide: {
      title: "使用教學",
      lede: "站在鏡頭前，讓手掌清楚入鏡。比出一個手勢並稍停一下；同一隻手大約一秒內不會連續觸發兩次。",
      pauseName: "暫停",
      pauseHow: "張開手掌，掌心朝向鏡頭。",
      playName: "播放",
      playHow: "豎起拇指（讚）。",
      switchName: "切換版面",
      switchHow: "勝利手勢（食指與中指）。站姿是左右分屏；墊上是教練在上、你在下。",
      rewindName: "倒帶 10 秒",
      rewindHow: "拇指朝下，或食指朝上。影片會往回跳十秒。",
      tipTitle: "小提示",
      tip1: "瀏覽器詢問鏡頭時請允許。鏡子畫面只留在這台裝置。",
      tip2: "一次一隻手，比兩隻手同時比劃更穩。",
      tip3: "若 YouTube 禁止內嵌，請改從訓練頁選 Pamela 課表。",
    },
    about: {
      title: "關於這個網頁",
      p1: "嗨，我是語仁 Rain Liu！",
      p2: "開發這個網站是因為自己本身很喜歡看 Pamela Reif 的影片居家健身。",
      p3: "因為要反覆到電腦前面調整實在太麻煩了（明明是健身還怕麻煩哈哈），所以就想做個網站讓我更方便選課與操作。",
      p4: "99%的程式設計都是Cursor Agent完成的，詳見github repo。完全開源、不營利。",
      p5: "除了用戶自選的健身影片連結，預設呈現的所有影片都是 Pamela 的 YouTube 教材。",
      p6: "與 Pamela Reif 沒有官方關係。若你喜歡這些內容，請到 YouTube 支持她。",
    },
    yt: {
      blocked: "YouTube 禁止內嵌這支影片。",
      open: "在 YouTube 開啟{title}",
      fallback: "這堂課",
      hint: "改從訓練頁選 Pamela 課表，那些已確認可內嵌。",
    },
  },
};
